services:
  mongo:
    image: mongo:latest
    container_name: mongo_dev
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db
    logging:
      driver: none

volumes:
  mongo_data:
